from __future__ import annotations

from typing import Literal


voice_options_big = {
    #通用
    "冷酷哥哥": "zh_male_lengkugege_emo_v2_mars_bigtts",
    "甜心小美": "zh_female_tianxinxiaomei_emo_v2_mars_bigtts",
    "高冷御姐": "zh_female_gaolengyujie_emo_v2_mars_bigtts",
    "傲娇霸总": "zh_male_aojiaobazong_emo_v2_mars_bigtts",
    "广州德哥": "zh_male_guangzhoudege_emo_mars_bigtts",
    "京腔侃爷": "zh_male_jingqiangkanye_emo_mars_bigtts",
    "邻居阿姨": "zh_female_linjuayi_emo_v2_mars_bigtts",
    "优柔公子": "zh_male_yourougongzi_emo_v2_mars_bigtts",
    "儒雅男友": "zh_male_ruyayichen_emo_v2_mars_bigtts",
    "俊朗男友": "zh_male_junlangnanyou_emo_v2_mars_bigtts",
    "北京小爷": "zh_male_beijingxiaoye_emo_v2_mars_bigtts",
    "柔美女友": "zh_female_roumeinvyou_emo_v2_mars_bigtts",
    "阳光青年": "zh_male_yangguangqingnian_emo_v2_mars_bigtts",
    "魅力女友": "zh_female_meilinvyou_emo_v2_mars_bigtts",
    "爽快思思": "zh_female_shuangkuaisisi_emo_v2_mars_bigtts",
    #趣味口音
    "沪普男": "zh_male_hupunan_mars_bigtts",
    "粤语小溏": "zh_female_yueyunv_mars_bigtts",
    "鲁班七号": "zh_male_lubanqihao_mars_bigtts",
    "林潇": "zh_female_yangmi_mars_bigtts",
    "玲玲姐姐": "zh_female_linzhiling_mars_bigtts",
    "春日部姐姐": "zh_female_jiyejizi2_mars_bigtts",
    "唐僧": "zh_male_tangseng_mars_bigtts",
    "庄周": "zh_male_zhuangzhou_mars_bigtts",
    "猪八戒": "zh_male_zhubajie_mars_bigtts",
    "感冒电音姐姐": "zh_female_ganmaodianyin_mars_bigtts",
    "直率英子": "zh_female_naying_mars_bigtts",
    "女雷神": "zh_female_leidian_mars_bigtts",
    "豫州子轩": "zh_male_yuzhouzixuan_moon_bigtts",
    "呆萌川妹": "zh_female_daimengchuanmei_moon_bigtts",
    "广西远舟": "zh_male_guangxiyuanzhou_moon_bigtts",
    "双节棍小哥": "zh_male_zhoujielun_emo_v2_mars_bigtts",
    "湾湾小何": "zh_female_wanwanxiaohe_moon_bigtts",
    "湾区大叔": "zh_female_wanqudashu_moon_bigtts",
    "浩宇小哥": "zh_male_haoyuxiaoge_moon_bigtts",
    "妹坨洁儿": "zh_female_meituojieer_moon_bigtts",
    # 角色扮演
    "纯真少女": "ICL_zh_female_chunzhenshaonv_e588402fb8ad_tob",
    "奶气小生": "ICL_zh_male_xiaonaigou_edf58cf28b8b_tob",
    "精灵向导": "ICL_zh_female_jinglingxiangdao_1beb294a9e3e_tob",
    "闷油瓶小哥": "ICL_zh_male_menyoupingxiaoge_ffed9fc2fee7_tob",
    "黯刃秦主": "ICL_zh_male_anrenqinzhu_cd62e63dcdab_tob",
    "霸道总裁": "ICL_zh_male_badaozongcai_v1_tob",
    "妩媚可人": "ICL_zh_female_ganli_v1_tob",
    "邪魅御姐": "ICL_zh_female_xiangliangya_v1_tob",
    "嚣张小哥": "ICL_zh_male_ms_tob",
    "油腻大叔": "ICL_zh_male_you_tob",
    "孤傲公子": "ICL_zh_male_guaogongzi_v1_tob",
    "胡子叔叔": "ICL_zh_male_huzi_v1_tob",
    "性感魅惑": "ICL_zh_female_luoqing_v1_tob",
    "病弱公子": "ICL_zh_male_bingruogongzi_tob",
    "邪魅女王": "ICL_zh_female_bingjiao3_tob",
    "傲慢青年": "ICL_zh_male_aomanqingnian_tob",
    "醋精男生": "ICL_zh_male_cujingnansheng_tob",
    "爽朗少年": "ICL_zh_male_shuanglangshaonian_tob",
    "撒娇男友": "ICL_zh_male_sajiaonanyou_tob",
    "温柔男友": "ICL_zh_male_wenrounanyou_tob",
    "温顺少年": "ICL_zh_male_wenshunshaonian_tob",
    "粘人男友": "ICL_zh_male_naigounanyou_tob",
    "撒娇男生": "ICL_zh_male_sajiaonansheng_tob",
    "活泼男友": "ICL_zh_male_huoponanyou_tob",
    "甜系男友": "ICL_zh_male_tianxinanyou_tob",
    "活力青年": "ICL_zh_male_huoliqingnian_tob",
    "开朗青年": "ICL_zh_male_kailangqingnian_tob",
    "冷漠兄长": "ICL_zh_male_lengmoxiongzhang_tob",
    "天才同桌": "ICL_zh_male_tiancaitongzhuo_tob",
    "翩翩公子": "ICL_zh_male_pianpiangongzi_tob",
    "懵懂青年": "ICL_zh_male_mengdongqingnian_tob",
    "冷脸兄长": "ICL_zh_male_lenglianxiongzhang_tob",
    "病娇少年": "ICL_zh_male_bingjiaoshaonian_tob",
    "病娇男友": "ICL_zh_male_bingjiaonanyou_tob",
    "病弱少年": "ICL_zh_male_bingruoshaonian_tob",
    "意气少年": "ICL_zh_male_yiqishaonian_tob",
    "干净少年": "ICL_zh_male_ganjingshaonian_tob",
    "冷漠男友": "ICL_zh_male_lengmonanyou_tob",
    "精英青年": "ICL_zh_male_jingyingqingnian_tob",
    "热血少年": "ICL_zh_male_rexueshaonian_tob",
    "清爽少年": "ICL_zh_male_qingshuangshaonian_tob",
    "中二青年": "ICL_zh_male_zhongerqingnian_tob",
    "凌云青年": "ICL_zh_male_lingyunqingnian_tob",
    "自负青年": "ICL_zh_male_zifuqingnian_tob",
    "不羁青年": "ICL_zh_male_bujiqingnian_tob",
    "儒雅君子": "ICL_zh_male_ruyajunzi_tob",
    "低音沉郁": "ICL_zh_male_diyinchenyu_tob",
    "冷脸学霸": "ICL_zh_male_lenglianxueba_tob",
    "儒雅总裁": "ICL_zh_male_ruyazongcai_tob",
    "深沉总裁": "ICL_zh_male_shenchenzongcai_tob",
    "小侯爷": "ICL_zh_male_xiaohouye_tob",
    "孤高公子": "ICL_zh_male_gugaogongzi_tob",
    "仗剑君子": "ICL_zh_male_zhangjianjunzi_tob",
    "温润学者": "ICL_zh_male_wenrunxuezhe_tob",
    "亲切青年": "ICL_zh_male_qinqieqingnian_tob",
    "温柔学长": "ICL_zh_male_wenrouxuezhang_tob",
    "高冷总裁": "ICL_zh_male_gaolengzongcai_tob",
    "冷峻高智": "ICL_zh_male_lengjungaozhi_tob",
    "孱弱少爷": "ICL_zh_male_chanruoshaoye_tob",
    "自信青年": "ICL_zh_male_zixinqingnian_tob",
    "青涩青年": "ICL_zh_male_qingseqingnian_tob",
    "学霸同桌": "ICL_zh_male_xuebatongzhuo_tob",
    "冷傲总裁": "ICL_zh_male_lengaozongcai_tob",
    "元气少年": "ICL_zh_male_yuanqishaonian_tob",
    "洒脱青年": "ICL_zh_male_satuoqingnian_tob",
    "直率青年": "ICL_zh_male_zhishuaiqingnian_tob",
    "斯文青年": "ICL_zh_male_siwenqingnian_tob",
    "俊逸公子": "ICL_zh_male_junyigongzi_tob",
    "仗剑侠客": "ICL_zh_male_zhangjianxiake_tob",
    "机甲智能": "ICL_zh_male_jijiaozhineng_tob",
    "奶气萌娃": "zh_male_naiqimengwa_mars_bigtts",
    "婆婆": "zh_female_popo_mars_bigtts",
    "高冷御姐2": "zh_female_gaolengyujie_moon_bigtts",
    "傲娇霸总2": "zh_male_aojiaobazong_moon_bigtts",
    "魅力女友2": "zh_female_meilinvyou_moon_bigtts",
    "深夜播客": "zh_male_shenyeboke_moon_bigtts",
    "柔美女友2": "zh_female_sajiaonvyou_moon_bigtts",
    "撒娇学妹": "zh_female_yuanqinvyou_moon_bigtts",
    "病弱少女": "ICL_zh_female_bingruoshaonv_tob",
    "活泼女孩": "ICL_zh_female_huoponvhai_tob",
    "东方浩然": "zh_male_dongfanghaoran_moon_bigtts",
    "绿茶小哥": "ICL_zh_male_lvchaxiaoge_tob",
    "娇弱萝莉": "ICL_zh_female_jiaoruoluoli_tob",
    "冷淡疏离": "ICL_zh_male_lengdanshuli_tob",
    "憨厚敦实": "ICL_zh_male_hanhoudunshi_tob",
    "活泼刁蛮": "ICL_zh_female_huopodiaoman_tob",
    "固执病娇": "ICL_zh_male_guzhibingjiao_tob",
    "撒娇粘人": "ICL_zh_male_sajiaonianren_tob",
    "傲慢娇声": "ICL_zh_female_aomanjiaosheng_tob",
    "潇洒随性": "ICL_zh_male_xiaosasuixing_tob",
    "诡异神秘": "ICL_zh_male_guiyishenmi_tob",
    "儒雅才俊": "ICL_zh_male_ruyacaijun_tob",
    "正直青年": "ICL_zh_male_zhengzhiqingnian_tob",
    "娇憨女王": "ICL_zh_female_jiaohannvwang_tob",
    "病娇萌妹": "ICL_zh_female_bingjiaomengmei_tob",
    "青涩小生": "ICL_zh_male_qingsenaigou_tob",
    "纯真学弟": "ICL_zh_male_chunzhenxuedi_tob",
    "优柔帮主": "ICL_zh_male_youroubangzhu_tob",
    "优柔公子2": "ICL_zh_male_yourougongzi_tob",
    "调皮公主": "ICL_zh_female_tiaopigongzhu_tob",
    "贴心男友": "ICL_zh_male_tiexinnanyou_tob",
    "少年将军": "ICL_zh_male_shaonianjiangjun_tob",
    "病娇哥哥": "ICL_zh_male_bingjiaogege_tob",
    "学霸男同桌": "ICL_zh_male_xuebanantongzhuo_tob",
    "幽默叔叔": "ICL_zh_male_youmoshushu_tob",
    "假小子": "ICL_zh_female_jiaxiaozi_tob",
    "温柔男同桌": "ICL_zh_male_wenrounantongzhuo_tob",
    "幽默大爷": "ICL_zh_male_youmodaye_tob",
    "枕边低语": "ICL_zh_male_asmryexiu_tob",
    "神秘法师": "ICL_zh_male_shenmifashi_tob",
    "娇喘女声": "zh_female_jiaochuan_mars_bigtts",
    "开朗弟弟": "zh_male_livelybro_mars_bigtts",
    "谄慢女声": "zh_female_flattery_mars_bigtts",
    "冷峻上司": "ICL_zh_male_lengjunshangsi_tob",
    #角色扮演 S2S-SC
    "醋精男友": "ICL_zh_male_cujingnanyou_tob",
    "风发少年": "ICL_zh_male_fengfashaonian_tob",
    "磁性男嗓": "ICL_zh_male_cixingnansang_tob",
    "成熟总裁": "ICL_zh_male_chengshuzongcai_tob",
    "傲娇精英": "ICL_zh_male_aojiaojingying_tob",
    "傲娇公子": "ICL_zh_male_aojiaogongzi_tob",
    "霸道少爷": "ICL_zh_male_badaoshaoye_tob",
    "腹黑公子": "ICL_zh_male_fuheigongzi_tob",
    "暖心学姐": "ICL_zh_female_nuanxinxuejie_tob",
    "可爱女生": "ICL_zh_female_keainvsheng_tob",
    "成熟姐姐": "ICL_zh_female_chengshujiejie_tob",
    "病娇姐姐": "ICL_zh_female_bingjiaojiejie_tob",
    "妩媚御姐": "ICL_zh_female_wumeiyujie_tob",
    "傲娇女友": "ICL_zh_female_aojiaonvyou_tob",
    "贴心女友": "ICL_zh_female_tiexinnvyou_tob",
    "性感御姐": "ICL_zh_female_xingganyujie_tob",
    "病娇弟弟": "ICL_zh_male_bingjiaodidi_tob",
    "傲慢少爷": "ICL_zh_male_aomanshaoye_tob",
    "傲气凌人": "ICL_zh_male_aiqilingren_tob",
    "病娇白莲": "ICL_zh_male_bingjiaobailian_tob",
    #客服
    "理性圆子": "ICL_zh_female_lixingyuanzi_cs_tob",
    "清甜桃桃": "ICL_zh_female_qingtiantaotao_cs_tob",
    "清晰小雪": "ICL_zh_female_qingxixiaoxue_cs_tob",
    "清甜莓莓": "ICL_zh_female_qingtianmeimei_cs_tob",
    "开朗婷婷": "ICL_zh_female_kailangtingting_cs_tob",
    "清新沐沐": "ICL_zh_male_qingxinmumu_cs_tob",
    "爽朗小阳": "ICL_zh_male_shuanglangxiaoyang_cs_tob",
    "清新波波": "ICL_zh_male_qingxinbobo_cs_tob",
    "温婉珊珊": "ICL_zh_female_wenwanshanshan_cs_tob",
    "甜美小雨": "ICL_zh_female_tianmeixiaoyu_cs_tob",
    "热情艾娜": "ICL_zh_female_reqingaina_cs_tob",
    "甜美小橘": "ICL_zh_female_tianmeixiaoju_cs_tob",
    "沉稳明仔": "ICL_zh_male_chenwenmingzai_cs_tob",
    "亲切小卓": "ICL_zh_male_qinqiexiaozhuo_cs_tob",
    "灵动欣欣": "ICL_zh_female_lingdongxinxin_cs_tob",
    "乖巧可儿": "ICL_zh_female_guaiqiaokeer_cs_tob",
    "暖心茜茜": "ICL_zh_female_nuanxinqianqian_cs_tob",
    "软萌团子": "ICL_zh_female_ruanmengtuanzi_cs_tob",
    "阳光洋洋": "ICL_zh_male_yangguangyangyang_cs_tob",
    "软萌糖糖": "ICL_zh_female_ruanmengtangtang_cs_tob",
    "秀丽倩倩": "ICL_zh_female_xiuliqianqian_cs_tob",
    "开心小鸿": "ICL_zh_female_kaixinxiaohong_cs_tob",
    "轻盈朵朵": "ICL_zh_female_qingyingduoduo_cs_tob",
    "暖阳女声": "zh_female_kefunvsheng_mars_bigtts",
    #视频配音
    "悠悠君子": "zh_male_M100_conversation_wvae_bigtts",
    "文静毛毛": "zh_female_maomao_conversation_wvae_bigtts",
    "倾心少女": "ICL_zh_female_qiuling_v1_tob",
    "醇厚低音": "ICL_zh_male_buyan_v1_tob",
    "咆哮小哥": "ICL_zh_male_BV144_paoxiaoge_v1_tob",
    "和蔼奶奶": "ICL_zh_female_heainainai_tob",
    "邻居阿姨2": "ICL_zh_female_linjuayi_tob",
    "温柔小雅": "zh_female_wenrouxiaoya_moon_bigtts",
    "天才童声": "zh_male_tiancaitongsheng_mars_bigtts",
    "猴哥": "zh_male_sunwukong_mars_bigtts",
    "熊二": "zh_male_xionger_mars_bigtts",
    "佩奇猪": "zh_female_peiqi_mars_bigtts",
    "武则天": "zh_female_wuzetian_mars_bigtts",
    "顾姐": "zh_female_gujie_mars_bigtts",
    "樱桃丸子": "zh_female_yingtaowanzi_mars_bigtts",
    "广告解说": "zh_male_chunhui_mars_bigtts",
    "少儿故事": "zh_female_shaoergushi_mars_bigtts",
    "四郎": "zh_male_silang_mars_bigtts",
    "俏皮女声": "zh_female_qiaopinvsheng_mars_bigtts",
    "懒音绵宝": "zh_male_lanxiaoyang_mars_bigtts",
    "亮嗓萌仔": "zh_male_dongmanhaimian_mars_bigtts",
    "磁性解说男声": "zh_male_jieshuonansheng_mars_bigtts",
    "鸡汤妹妹": "zh_female_jitangmeimei_mars_bigtts",
    "贴心女声": "zh_female_tiexinnvsheng_mars_bigtts",
    "萌丫头": "zh_female_mengyatou_mars_bigtts",
    #新增
    "Vivi": "zh_female_vv_mars_bigtts",
    "机灵小伙": "ICL_zh_male_shenmi_v1_tob",
    "温暖少年": "ICL_zh_male_yangyang_v1_tob",
    "开朗轻快": "ICL_zh_male_kailangqingkuai_tob",
    "擎苍": "zh_male_qingcang_mars_bigtts",
    "心灵鸡汤": "zh_female_xinlingjitang_moon_bigtts",
    "甜美悦悦": "zh_female_tianmeiyueyue_moon_bigtts",
}

voice_options_small = {
    # 通用场景
    "天才少女": "BV421_streaming",
    "灿灿 2.0": "BV700_V2_streaming",
    "炀炀": "BV705_streaming",
    "擎苍 2.0": "BV701_V2_streaming",
    "通用女声 2.0": "BV001_V2_streaming",
    "灿灿": "BV700_streaming",
    "超自然音色-梓梓2.0": "BV406_V2_streaming",
    "超自然音色-梓梓": "BV406_streaming",
    "超自然音色-燃燃2.0": "BV407_V2_streaming",
    "超自然音色-燃燃": "BV407_streaming",
    "通用女声": "BV001_streaming",
    "通用男声": "BV002_streaming",
    # 有声阅读
    "擎苍": "BV701_streaming",
    "阳光青年": "BV123_streaming",
    "反卷青年": "BV120_streaming",
    "通用赘婿": "BV119_streaming",
    "古风少御": "BV115_streaming",
    "霸气青叔": "BV107_streaming",
    "质朴青年": "BV100_streaming",
    "温柔淑女": "BV104_streaming",
    "开朗青年": "BV004_streaming",
    "甜宠少御": "BV113_streaming",
    "儒雅青年": "BV102_streaming",
    # 智能助手
    "甜美小源": "BV405_streaming",
    "亲切女声": "BV007_streaming",
    "知性女声": "BV009_streaming",
    "诚诚": "BV419_streaming",
    "童童": "BV415_streaming",
    "亲切男声": "BV008_streaming",
    # 视频配音
    "译制片男声": "BV408_streaming",
    "懒小羊": "BV426_streaming",
    "清新文艺女声": "BV428_streaming",
    "鸡汤女声": "BV403_streaming",
    "智慧老者": "BV158_streaming",
    "慈爱姥姥": "BV157_streaming",
    "说唱小哥": "BR001_streaming",
    "活力解说男": "BV410_streaming",
    "影视解说小帅": "BV411_streaming",
    "解说小帅-多情感": "BV437_streaming",
    "影视解说小美": "BV412_streaming",
    "纨绔青年": "BV159_streaming",
    "直播一姐": "BV418_streaming",
    "沉稳解说男": "BV142_streaming",
    "潇洒青年": "BV143_streaming",
    "阳光男声": "BV056_streaming",
    "活泼女声": "BV005_streaming",
    "小萝莉": "BV064_streaming",
    # 特色音色
    "奶气萌娃": "BV051_streaming",
    "动漫海绵": "BV063_streaming",
    "动漫海星": "BV417_streaming",
    "动漫小新": "BV050_streaming",
    "天才童声": "BV061_streaming",
    # 广告配音
    "促销男声": "BV401_streaming",
    "促销女声": "BV402_streaming",
    "磁性男声": "BV006_streaming",
    # 新闻播报
    "新闻女声": "BV011_streaming",
    "新闻男声": "BV012_streaming",
    # 教育场景
    "知性姐姐-双语": "BV034_streaming",
    "温柔小哥": "BV033_streaming",
}

voice_options = {
    "big": voice_options_big,
    "small": voice_options_small,
}

volcano_voice_options = voice_options

character_options = {**voice_options_big, **voice_options_small}

voice_model_type_options = ("big", "small")


def get_volcano_voice_type(voice_character: str) -> Literal["big", "small"]:
    if voice_character in voice_options_small:
        return "small"
    if voice_character in voice_options_big:
        return "big"
    raise KeyError(f"Unknown volcovoice character: {voice_character}")


def get_voice_options(model_type: str = "all") -> dict[str, str]:
    normalized = (model_type or "all").lower()
    if normalized == "all":
        return character_options
    if normalized == "big":
        return voice_options_big
    if normalized == "small":
        return voice_options_small
    raise ValueError("model_type must be one of: all, big, small")

__all__ = [
    'voice_options_big',
    'voice_options_small',
    'voice_options',
    'volcano_voice_options',
    'character_options',
    'voice_model_type_options',
    'get_volcano_voice_type',
    'get_voice_options',
    'voice_enums_meta',
]

from models.voice_enums_meta import voice_enums_meta
