from __future__ import annotations

from typing import Literal


voice_options_big = {
    "Candice": "en_female_candice_emo_v2_mars_bigtts",
    "Corey": "en_male_corey_emo_v2_mars_bigtts",
    "Dacey": "en_female_dacey_uranus_bigtts",
    "Dacey 2.0": "en_female_dacey_uranus_bigtts",
    "Glen": "en_male_glen_emo_v2_mars_bigtts",
    "Nadia": "en_female_nadia_tips_emo_v2_mars_bigtts",
    "Serena": "en_female_skye_emo_v2_mars_bigtts",
    "Stokie": "en_female_stokie_uranus_bigtts",
    "Stokie 2.0": "en_female_stokie_uranus_bigtts",
    "Sylus": "en_male_sylus_emo_v2_mars_bigtts",
    "TVB女声": "zh_female_tvbnv_uranus_bigtts",
    "TVB女声 2.0": "zh_female_tvbnv_uranus_bigtts",
    "Tim": "en_male_tim_uranus_bigtts",
    "Tim 2.0": "en_male_tim_uranus_bigtts",
    "Tina老师": "zh_female_yingyujiaoxue_uranus_bigtts",
    "Tina老师 2.0": "zh_female_yingyujiaoxue_uranus_bigtts",
    "Vivi": "zh_female_vv_mars_bigtts",
    "Vivi 2.0": "zh_female_vv_uranus_bigtts",
    "vivi": "zh_female_vv_jupiter_bigtts",
    "vivi (Jupiter)": "zh_female_vv_jupiter_bigtts",
    "vivi (S2S-Omni)": "zh_female_vv_jupiter_bigtts",
    "不羁青年": "ICL_zh_male_bujiqingnian_tob",
    "不羁青年 (SC 2.0)": "saturn_zh_male_bujiqingnian_tob",
    "不羁青年 (Saturn)": "saturn_zh_male_bujiqingnian_tob",
    "不羁青年 2.0": "saturn_zh_male_bujiqingnian_tob",
    "东方浩然": "zh_male_dongfanghaoran_moon_bigtts",
    "东方浩然 2.0": "zh_male_dongfanghaoran_uranus_bigtts",
    "中二青年": "ICL_zh_male_zhongerqingnian_tob",
    "乖巧可儿": "ICL_zh_female_guaiqiaokeer_cs_tob",
    "云舟": "zh_male_yunzhou_jupiter_bigtts",
    "云舟 (Jupiter)": "zh_male_yunzhou_jupiter_bigtts",
    "云舟 (S2S-Omni)": "zh_male_yunzhou_jupiter_bigtts",
    "云舟 2.0": "zh_male_m191_uranus_bigtts",
    "京腔侃爷": "zh_male_jingqiangkanye_emo_mars_bigtts",
    "京腔侃爷/Harmony": "zh_male_jingqiangkanye_moon_bigtts",
    "京腔侃爷（多情感）": "zh_male_jingqiangkanye_emo_mars_bigtts",
    "亮嗓萌仔": "zh_male_dongmanhaimian_mars_bigtts",
    "亮嗓萌仔 2.0": "zh_male_liangsangmengzai_uranus_bigtts",
    "亲切女声": "zh_female_qinqienvsheng_moon_bigtts",
    "亲切女声 2.0": "zh_female_qinqienv_uranus_bigtts",
    "亲切小卓": "ICL_zh_male_qinqiexiaozhuo_cs_tob",
    "亲切青年": "ICL_zh_male_qinqieqingnian_tob",
    "仗剑侠客": "ICL_zh_male_zhangjianxiake_tob",
    "仗剑君子": "ICL_zh_male_zhangjianjunzi_tob",
    "优柔公子": "zh_male_yourougongzi_emo_v2_mars_bigtts",
    "优柔公子2": "ICL_zh_male_yourougongzi_tob",
    "优柔公子（多情感）": "zh_male_yourougongzi_emo_v2_mars_bigtts",
    "优柔帮主": "ICL_zh_male_youroubangzhu_tob",
    "低沉缱绻": "ICL_zh_male_sigeshiye_v1_tob",
    "低音沉郁": "ICL_zh_male_diyinchenyu_tob",
    "佩奇猪": "zh_female_peiqi_mars_bigtts",
    "佩奇猪 2.0": "zh_female_peiqi_uranus_bigtts",
    "俊朗男友": "zh_male_junlangnanyou_emo_v2_mars_bigtts",
    "俊朗男友（多情感）": "zh_male_junlangnanyou_emo_v2_mars_bigtts",
    "俊逸公子": "ICL_zh_male_junyigongzi_tob",
    "俏皮女声": "zh_female_qiaopinvsheng_mars_bigtts",
    "俏皮女声 2.0": "zh_female_qiaopinv_uranus_bigtts",
    "倾心少女": "ICL_zh_female_qiuling_v1_tob",
    "假小子": "ICL_zh_female_jiaxiaozi_tob",
    "傲娇公子": "ICL_zh_male_aojiaogongzi_tob",
    "傲娇公子 (SC 2.0)": "saturn_zh_male_aojiaogongzi_tob",
    "傲娇公子 (Saturn)": "saturn_zh_male_aojiaogongzi_tob",
    "傲娇公子 2.0": "saturn_zh_male_aojiaogongzi_tob",
    "傲娇女友": "ICL_zh_female_aojiaonvyou_tob",
    "傲娇女友 (SC 2.0)": "saturn_zh_female_aojiaonvyou_tob",
    "傲娇女友 (Saturn)": "saturn_zh_female_aojiaonvyou_tob",
    "傲娇女友 2.0": "saturn_zh_female_aojiaonvyou_tob",
    "傲娇精英": "ICL_zh_male_aojiaojingying_tob",
    "傲娇精英 (SC 2.0)": "saturn_zh_male_aojiaojingying_tob",
    "傲娇精英 (Saturn)": "saturn_zh_male_aojiaojingying_tob",
    "傲娇精英 2.0": "saturn_zh_male_aojiaojingying_tob",
    "傲娇霸总": "zh_male_aojiaobazong_emo_v2_mars_bigtts",
    "傲娇霸总 2.0": "zh_male_aojiaobazong_uranus_bigtts",
    "傲娇霸总2": "zh_male_aojiaobazong_moon_bigtts",
    "傲娇霸总（多情感）": "zh_male_aojiaobazong_emo_v2_mars_bigtts",
    "傲慢娇声": "ICL_zh_female_aomanjiaosheng_tob",
    "傲慢少爷": "ICL_zh_male_aomanshaoye_tob",
    "傲慢少爷 (SC 2.0)": "saturn_zh_male_aomanshaoye_tob",
    "傲慢少爷 (Saturn)": "saturn_zh_male_aomanshaoye_tob",
    "傲慢少爷 2.0": "saturn_zh_male_aomanshaoye_tob",
    "傲慢青年": "ICL_zh_male_aomanqingnian_tob",
    "傲气凌人": "ICL_zh_male_aiqilingren_tob",
    "傲气凌人 (SC 2.0)": "saturn_zh_male_aiqilingren_tob",
    "傲气凌人 (Saturn)": "saturn_zh_male_aiqilingren_tob",
    "傲气凌人 2.0": "saturn_zh_male_aiqilingren_tob",
    "儒雅君子": "ICL_zh_male_ruyajunzi_tob",
    "儒雅总裁": "ICL_zh_male_ruyazongcai_tob",
    "儒雅才俊": "ICL_zh_male_ruyacaijun_tob",
    "儒雅男友": "zh_male_ruyayichen_emo_v2_mars_bigtts",
    "儒雅男友（多情感）": "zh_male_ruyayichen_emo_v2_mars_bigtts",
    "儒雅逸辰": "zh_male_ruyayichen_uranus_bigtts",
    "儒雅逸辰 2.0": "zh_male_ruyayichen_uranus_bigtts",
    "儒雅青年 2.0": "zh_male_ruyaqingnian_uranus_bigtts",
    "儿童绘本": "zh_female_xiaoxue_uranus_bigtts",
    "儿童绘本 2.0": "zh_female_xiaoxue_uranus_bigtts",
    "元气少年": "ICL_zh_male_yuanqishaonian_tob",
    "元气甜妹": "ICL_zh_female_wuxi_tob",
    "冷傲总裁": "ICL_zh_male_lengaozongcai_tob",
    "冷峻上司": "ICL_zh_male_lengjunshangsi_tob",
    "冷峻高智": "ICL_zh_male_lengjungaozhi_tob",
    "冷淡疏离": "ICL_zh_male_lengdanshuli_tob",
    "冷漠兄长": "ICL_zh_male_lengmoxiongzhang_tob",
    "冷漠男友": "ICL_zh_male_lengmonanyou_tob",
    "冷脸兄长": "ICL_zh_male_lenglianxiongzhang_tob",
    "冷脸学霸": "ICL_zh_male_lenglianxueba_tob",
    "冷酷哥哥": "zh_male_lengkugege_emo_v2_mars_bigtts",
    "冷酷哥哥（多情感）": "zh_male_lengkugege_emo_v2_mars_bigtts",
    "凌云青年": "ICL_zh_male_lingyunqingnian_tob",
    "刘飞": "zh_male_liufei_uranus_bigtts",
    "刘飞 2.0": "zh_male_liufei_uranus_bigtts",
    "初恋女友": "ICL_zh_female_yuxin_v1_tob",
    "北京小爷": "zh_male_beijingxiaoye_emo_v2_mars_bigtts",
    "北京小爷（多情感）": "zh_male_beijingxiaoye_emo_v2_mars_bigtts",
    "双节棍小哥": "zh_male_zhoujielun_emo_v2_mars_bigtts",
    "反卷青年 2.0": "zh_male_fanjuanqingnian_uranus_bigtts",
    "古风少御 2.0": "zh_female_gufengshaoyu_uranus_bigtts",
    "可爱女生": "ICL_zh_female_keainvsheng_tob",
    "可爱女生 (SC 2.0)": "saturn_zh_female_keainvsheng_tob",
    "可爱女生 (Saturn)": "saturn_zh_female_keainvsheng_tob",
    "可爱女生 2.0": "saturn_zh_female_keainvsheng_tob",
    "呆萌川妹": "zh_female_daimengchuanmei_moon_bigtts",
    "咆哮小哥": "ICL_zh_male_BV144_paoxiaoge_v1_tob",
    "和蔼奶奶": "ICL_zh_female_heainainai_tob",
    "唐僧": "zh_male_tangseng_mars_bigtts",
    "唐僧 2.0": "zh_male_tangseng_uranus_bigtts",
    "嚣张小哥": "ICL_zh_male_ms_tob",
    "四郎": "zh_male_silang_mars_bigtts",
    "四郎 2.0": "zh_male_silang_uranus_bigtts",
    "固执病娇": "ICL_zh_male_guzhibingjiao_tob",
    "大壹": "zh_male_dayi_uranus_bigtts",
    "大壹 2.0": "zh_male_dayi_uranus_bigtts",
    "天才同桌": "ICL_zh_male_tiancaitongzhuo_tob",
    "天才同桌 (SC 2.0)": "saturn_zh_male_tiancaitongzhuo_tob",
    "天才同桌 (Saturn)": "saturn_zh_male_tiancaitongzhuo_tob",
    "天才同桌 2.0": "saturn_zh_male_tiancaitongzhuo_tob",
    "天才童声": "zh_male_tiancaitongsheng_mars_bigtts",
    "天才童声 2.0": "zh_male_tiancaitongsheng_uranus_bigtts",
    "女雷神": "zh_female_leidian_mars_bigtts",
    "女雷神 2.0": "zh_female_nvleishen_uranus_bigtts",
    "奶气小生": "ICL_zh_male_xiaonaigou_edf58cf28b8b_tob",
    "奶气萌娃": "zh_male_naiqimengwa_mars_bigtts",
    "奶气萌娃 2.0": "zh_male_naiqimengwa_uranus_bigtts",
    "妩媚可人": "ICL_zh_female_ganli_v1_tob",
    "妩媚御姐": "ICL_zh_female_wumeiyujie_tob",
    "妩媚御姐 (SC 2.0)": "saturn_zh_female_wumeiyujie_tob",
    "妩媚御姐 (Saturn)": "saturn_zh_female_wumeiyujie_tob",
    "妩媚御姐 2.0": "saturn_zh_female_wumeiyujie_tob",
    "妹坨洁儿": "zh_female_meituojieer_moon_bigtts",
    "娇喘女声": "zh_female_jiaochuan_mars_bigtts",
    "娇喘女声 2.0": "zh_female_jiaochuannv_uranus_bigtts",
    "娇弱萝莉": "ICL_zh_female_jiaoruoluoli_tob",
    "娇憨女王": "ICL_zh_female_jiaohannvwang_tob",
    "婆婆": "zh_female_popo_mars_bigtts",
    "婆婆 2.0": "zh_female_popo_uranus_bigtts",
    "孤傲公子": "ICL_zh_male_guaogongzi_v1_tob",
    "孤高公子": "ICL_zh_male_gugaogongzi_tob",
    "学霸同桌": "ICL_zh_male_xuebatongzhuo_tob",
    "学霸男同桌": "ICL_zh_male_xuebanantongzhuo_tob",
    "孱弱少爷": "ICL_zh_male_chanruoshaoye_tob",
    "寡言小哥": "ICL_zh_male_xiaoge_v1_tob",
    "小何": "zh_female_xiaohe_jupiter_bigtts",
    "小何 (Jupiter)": "zh_female_xiaohe_jupiter_bigtts",
    "小何 (S2S-Omni)": "zh_female_xiaohe_jupiter_bigtts",
    "小何 2.0": "zh_female_xiaohe_uranus_bigtts",
    "小侯爷": "ICL_zh_male_xiaohouye_tob",
    "小天": "zh_male_xiaotian_jupiter_bigtts",
    "小天 (Jupiter)": "zh_male_xiaotian_jupiter_bigtts",
    "小天 (S2S-Omni)": "zh_male_xiaotian_jupiter_bigtts",
    "小天 2.0": "zh_male_taocheng_uranus_bigtts",
    "少儿故事": "zh_female_shaoergushi_mars_bigtts",
    "少儿故事 2.0": "zh_female_shaoergushi_uranus_bigtts",
    "少年将军": "ICL_zh_male_shaonianjiangjun_tob",
    "少年梓辛/Brayan": "zh_male_shaonianzixin_moon_bigtts",
    "少年梓辛/Brayan 2.0": "zh_male_shaonianzixin_uranus_bigtts",
    "干净少年": "ICL_zh_male_ganjingshaonian_tob",
    "幽默叔叔": "ICL_zh_male_youmoshushu_tob",
    "幽默大爷": "ICL_zh_male_youmodaye_tob",
    "广告解说": "zh_male_chunhui_mars_bigtts",
    "广告解说 2.0": "zh_male_guanggaojieshuo_uranus_bigtts",
    "广州德哥": "zh_male_guangzhoudege_emo_mars_bigtts",
    "广州德哥（多情感）": "zh_male_guangzhoudege_emo_mars_bigtts",
    "广西远舟": "zh_male_guangxiyuanzhou_moon_bigtts",
    "庄周": "zh_male_zhuangzhou_mars_bigtts",
    "庄周 2.0": "zh_male_zhuangzhou_uranus_bigtts",
    "开心小鸿": "ICL_zh_female_kaixinxiaohong_cs_tob",
    "开朗姐姐": "zh_female_kailangjiejie_moon_bigtts",
    "开朗姐姐 2.0": "zh_female_kailangjiejie_uranus_bigtts",
    "开朗婷婷": "ICL_zh_female_kailangtingting_cs_tob",
    "开朗学长": "en_male_jason_conversation_wvae_bigtts",
    "开朗学长 2.0": "zh_male_kailangxuezhang_uranus_bigtts",
    "开朗弟弟": "zh_male_livelybro_mars_bigtts",
    "开朗弟弟 2.0": "zh_male_kailangdidi_uranus_bigtts",
    "开朗轻快": "ICL_zh_male_kailangqingkuai_tob",
    "开朗青年": "ICL_zh_male_kailangqingnian_tob",
    "心灵鸡汤": "zh_female_xinlingjitang_moon_bigtts",
    "心灵鸡汤 2.0": "zh_female_xinlingjitang_uranus_bigtts",
    "快乐小东": "zh_male_xudong_conversation_wvae_bigtts",
    "快乐小东 2.0": "zh_male_kuailexiaodong_uranus_bigtts",
    "性感御姐": "ICL_zh_female_xingganyujie_tob",
    "性感御姐 (SC 2.0)": "saturn_zh_female_xingganyujie_tob",
    "性感御姐 (Saturn)": "saturn_zh_female_xingganyujie_tob",
    "性感御姐 2.0": "saturn_zh_female_xingganyujie_tob",
    "性感魅惑": "ICL_zh_female_luoqing_v1_tob",
    "悠悠君子": "zh_male_M100_conversation_wvae_bigtts",
    "悠悠君子 2.0": "zh_male_youyoujunzi_uranus_bigtts",
    "悠游君子 2.0": "zh_male_youyoujunzi_uranus_bigtts",
    "悬疑解说": "zh_male_xuanyijieshuo_uranus_bigtts",
    "悬疑解说 2.0": "zh_male_xuanyijieshuo_uranus_bigtts",
    "意气少年": "ICL_zh_male_yiqishaonian_tob",
    "感冒电音姐姐": "zh_female_ganmaodianyin_mars_bigtts",
    "感冒电音姐姐 2.0": "zh_female_ganmaodianyin_uranus_bigtts",
    "憨厚敦实": "ICL_zh_male_hanhoudunshi_tob",
    "懒音绵宝": "zh_male_lanxiaoyang_mars_bigtts",
    "懒音绵宝 2.0": "zh_male_lanyinmianbao_uranus_bigtts",
    "懵懂青年": "ICL_zh_male_mengdongqingnian_tob",
    "成熟姐姐": "ICL_zh_female_chengshujiejie_tob",
    "成熟姐姐 (SC 2.0)": "saturn_zh_female_chengshujiejie_tob",
    "成熟姐姐 (Saturn)": "saturn_zh_female_chengshujiejie_tob",
    "成熟姐姐 2.0": "saturn_zh_female_chengshujiejie_tob",
    "成熟总裁": "ICL_zh_male_chengshuzongcai_tob",
    "成熟总裁 (SC 2.0)": "saturn_zh_male_chengshuzongcai_tob",
    "成熟总裁 (Saturn)": "saturn_zh_male_chengshuzongcai_tob",
    "成熟总裁 2.0": "saturn_zh_male_chengshuzongcai_tob",
    "成熟温柔": "ICL_zh_female_chengshu_v1_tob",
    "撒娇学妹": "zh_female_yuanqinvyou_moon_bigtts",
    "撒娇学妹 2.0": "zh_female_sajiaoxuemei_uranus_bigtts",
    "撒娇男友": "ICL_zh_male_sajiaonanyou_tob",
    "撒娇男生": "ICL_zh_male_sajiaonansheng_tob",
    "撒娇粘人": "ICL_zh_male_sajiaonianren_tob",
    "擎苍": "zh_male_qingcang_mars_bigtts",
    "擎苍 2.0": "zh_male_qingcang_uranus_bigtts",
    "文静毛毛": "zh_female_maomao_conversation_wvae_bigtts",
    "文静毛毛 2.0": "zh_female_wenjingmaomao_uranus_bigtts",
    "斯文青年": "ICL_zh_male_siwenqingnian_tob",
    "春日部姐姐": "zh_female_jiyejizi2_mars_bigtts",
    "春日部姐姐 2.0": "zh_female_chunribu_uranus_bigtts",
    "暖心体贴": "ICL_zh_male_nuanxintitie_tob",
    "暖心学姐": "ICL_zh_female_nuanxinxuejie_tob",
    "暖心学姐 (SC 2.0)": "saturn_zh_female_nuanxinxuejie_tob",
    "暖心学姐 (Saturn)": "saturn_zh_female_nuanxinxuejie_tob",
    "暖心学姐 2.0": "saturn_zh_female_nuanxinxuejie_tob",
    "暖心茜茜": "ICL_zh_female_nuanxinqianqian_cs_tob",
    "暖阳女声": "zh_female_kefunvsheng_mars_bigtts",
    "暖阳女声 2.0": "zh_female_kefunvsheng_uranus_bigtts",
    "机灵小伙": "ICL_zh_male_shenmi_v1_tob",
    "机甲智能": "ICL_zh_male_jijiaozhineng_tob",
    "枕边低语": "ICL_zh_male_asmryexiu_tob",
    "林潇": "zh_female_yangmi_mars_bigtts",
    "林潇 2.0": "zh_female_linxiao_uranus_bigtts",
    "柔美女友": "zh_female_roumeinvyou_emo_v2_mars_bigtts",
    "柔美女友 2.0": "zh_female_roumeinvyou_uranus_bigtts",
    "柔美女友2": "zh_female_sajiaonvyou_moon_bigtts",
    "柔美女友（多情感）": "zh_female_roumeinvyou_emo_v2_mars_bigtts",
    "柔骨魂师": "ICL_zh_female_rouguhunshi_v1_tob",
    "樱桃丸子": "zh_female_yingtaowanzi_mars_bigtts",
    "樱桃丸子 2.0": "zh_female_yingtaowanzi_uranus_bigtts",
    "正直青年": "ICL_zh_male_zhengzhiqingnian_tob",
    "武则天": "zh_female_wuzetian_mars_bigtts",
    "武则天 2.0": "zh_female_wuzetian_uranus_bigtts",
    "沉稳优雅": "ICL_zh_male_qinglen_v1_tob",
    "沉稳明仔": "ICL_zh_male_chenwenmingzai_cs_tob",
    "沪普男": "zh_male_hupunan_mars_bigtts",
    "油腻大叔": "ICL_zh_male_you_tob",
    "洒脱青年": "ICL_zh_male_satuoqingnian_tob",
    "活力小哥": "zh_male_huolixiaoge_uranus_bigtts",
    "活力小哥 2.0": "zh_male_huolixiaoge_uranus_bigtts",
    "活力青年": "ICL_zh_male_huoliqingnian_tob",
    "活泼刁蛮": "ICL_zh_female_huopodiaoman_tob",
    "活泼女孩": "ICL_zh_female_huoponvhai_tob",
    "活泼爽朗": "ICL_zh_male_huoposhuanglang_tob",
    "活泼男友": "ICL_zh_male_huoponanyou_tob",
    "流畅女声": "zh_female_liuchangnv_uranus_bigtts",
    "流畅女声 2.0": "zh_female_liuchangnv_uranus_bigtts",
    "浩宇小哥": "zh_male_haoyuxiaoge_moon_bigtts",
    "深夜播客": "zh_male_shenyeboke_moon_bigtts",
    "深夜播客 2.0": "zh_male_shenyeboke_uranus_bigtts",
    "深沉总裁": "ICL_zh_male_shenchenzongcai_tob",
    "清冷矜贵": "ICL_zh_male_liyisheng_v1_tob",
    "清冷高雅": "ICL_zh_female_liumengdie_v1_tob",
    "清新女声": "zh_female_qingxinnvsheng_mars_bigtts",
    "清新女声 2.0": "zh_female_qingxinnvsheng_uranus_bigtts",
    "清新沐沐": "ICL_zh_male_qingxinmumu_cs_tob",
    "清新沐沐 (SC 2.0)": "saturn_zh_male_qingxinmumu_cs_tob",
    "清新沐沐 (Saturn)": "saturn_zh_male_qingxinmumu_cs_tob",
    "清新沐沐 2.0": "saturn_zh_male_qingxinmumu_cs_tob",
    "清新波波": "ICL_zh_male_qingxinbobo_cs_tob",
    "清晰小雪": "ICL_zh_female_qingxixiaoxue_cs_tob",
    "清朗温润": "ICL_zh_male_renyuwangzi_v1_tob",
    "清澈梓梓": "zh_female_qingchezizi_moon_bigtts",
    "清澈梓梓 2.0": "zh_female_qingchezizi_uranus_bigtts",
    "清爽少年": "ICL_zh_male_qingshuangshaonian_tob",
    "清爽男大": "zh_male_qingshuangnanda_mars_bigtts",
    "清爽男大 2.0": "zh_male_qingshuangnanda_uranus_bigtts",
    "清甜桃桃": "ICL_zh_female_qingtiantaotao_cs_tob",
    "清甜莓莓": "ICL_zh_female_qingtianmeimei_cs_tob",
    "清逸苏感": "ICL_zh_male_chongqingzhanzhan_v1_tob",
    "渊博小叔": "zh_male_yuanboxiaoshu_moon_bigtts",
    "渊博小叔 2.0": "zh_male_yuanboxiaoshu_uranus_bigtts",
    "温婉珊珊": "ICL_zh_female_wenwanshanshan_cs_tob",
    "温婉珊珊 (SC 2.0)": "saturn_zh_female_wenwanshanshan_cs_tob",
    "温婉珊珊 (Saturn)": "saturn_zh_female_wenwanshanshan_cs_tob",
    "温婉珊珊 2.0": "saturn_zh_female_wenwanshanshan_cs_tob",
    "温暖少年": "ICL_zh_male_yangyang_v1_tob",
    "温暖阿虎/Alvin": "zh_male_wennuanahu_moon_bigtts",
    "温暖阿虎/Alvin 2.0": "zh_male_wennuanahu_uranus_bigtts",
    "温柔内敛": "ICL_zh_male_xingjiwangzi_v1_tob",
    "温柔女神": "ICL_zh_female_wenrounvshen_239eff5e8ffa_tob",
    "温柔妈妈": "zh_female_wenroumama_uranus_bigtts",
    "温柔妈妈 2.0": "zh_female_wenroumama_uranus_bigtts",
    "温柔学长": "ICL_zh_male_wenrouxuezhang_tob",
    "温柔小哥": "zh_male_wenrouxiaoge_mars_bigtts",
    "温柔小哥 2.0": "zh_male_wenrouxiaoge_uranus_bigtts",
    "温柔小雅": "zh_female_wenrouxiaoya_moon_bigtts",
    "温柔小雅 2.0": "zh_female_wenrouxiaoya_uranus_bigtts",
    "温柔文雅": "saturn_zh_female_wenrouwenya_tob",
    "温柔文雅 (SC 2.0)": "saturn_zh_female_wenrouwenya_tob",
    "温柔文雅 (Saturn)": "saturn_zh_female_wenrouwenya_tob",
    "温柔文雅 2.0": "saturn_zh_female_wenrouwenya_tob",
    "温柔淑女 2.0": "zh_female_wenroushunv_uranus_bigtts",
    "温柔男友": "ICL_zh_male_wenrounanyou_tob",
    "温柔男同桌": "ICL_zh_male_wenrounantongzhuo_tob",
    "温柔白月光": "ICL_zh_female_yry_tob",
    "温润学者": "ICL_zh_male_wenrunxuezhe_tob",
    "温顺少年": "ICL_zh_male_wenshunshaonian_tob",
    "湾区大叔": "zh_female_wanqudashu_moon_bigtts",
    "湾湾小何": "zh_female_wanwanxiaohe_moon_bigtts",
    "潇洒随性": "ICL_zh_male_xiaosasuixing_tob",
    "灵动欣欣": "ICL_zh_female_lingdongxinxin_cs_tob",
    "灿灿/Shiny": "zh_female_cancan_mars_bigtts",
    "热情艾娜": "ICL_zh_female_reqingaina_cs_tob",
    "热情艾娜 (SC 2.0)": "saturn_zh_female_reqingaina_cs_tob",
    "热情艾娜 (Saturn)": "saturn_zh_female_reqingaina_cs_tob",
    "热情艾娜 2.0": "saturn_zh_female_reqingaina_cs_tob",
    "热血少年": "ICL_zh_male_rexueshaonian_tob",
    "熊二": "zh_male_xionger_mars_bigtts",
    "熊二 2.0": "zh_male_xionger_uranus_bigtts",
    "爽快思思": "zh_female_shuangkuaisisi_emo_v2_mars_bigtts",
    "爽快思思 2.0": "zh_female_shuangkuaisisi_uranus_bigtts",
    "爽快思思/Skye": "zh_female_shuangkuaisisi_moon_bigtts",
    "爽快思思（多情感）": "zh_female_shuangkuaisisi_emo_v2_mars_bigtts",
    "爽朗小阳": "ICL_zh_male_shuanglangxiaoyang_cs_tob",
    "爽朗少年": "ICL_zh_male_shuanglangshaonian_tob",
    "爽朗少年 (SC 2.0)": "saturn_zh_male_shuanglangshaonian_tob",
    "爽朗少年 (Saturn)": "saturn_zh_male_shuanglangshaonian_tob",
    "爽朗少年 2.0": "saturn_zh_male_shuanglangshaonian_tob",
    "猪八戒": "zh_male_zhubajie_mars_bigtts",
    "猪八戒 2.0": "zh_male_zhubajie_uranus_bigtts",
    "猴哥": "zh_male_sunwukong_mars_bigtts",
    "猴哥 2.0": "zh_male_sunwukong_uranus_bigtts",
    "率真小伙": "ICL_zh_male_shuaizhenxiaohuo_tob",
    "玲玲姐姐": "zh_female_linzhiling_mars_bigtts",
    "玲玲姐姐 2.0": "zh_female_lingling_uranus_bigtts",
    "理性圆子": "ICL_zh_female_lixingyuanzi_cs_tob",
    "甜心小美": "zh_female_tianxinxiaomei_emo_v2_mars_bigtts",
    "甜心小美（多情感）": "zh_female_tianxinxiaomei_emo_v2_mars_bigtts",
    "甜系男友": "ICL_zh_male_tianxinanyou_tob",
    "甜美娇俏": "ICL_zh_female_linxueying_v1_tob",
    "甜美小橘": "ICL_zh_female_tianmeixiaoju_cs_tob",
    "甜美小源": "zh_female_tianmeixiaoyuan_moon_bigtts",
    "甜美小源 2.0": "zh_female_tianmeixiaoyuan_uranus_bigtts",
    "甜美小雨": "ICL_zh_female_tianmeixiaoyu_cs_tob",
    "甜美悦悦": "zh_female_tianmeiyueyue_moon_bigtts",
    "甜美悦悦 2.0": "zh_female_tianmeiyueyue_uranus_bigtts",
    "甜美桃子": "zh_female_tianmeitaozi_mars_bigtts",
    "甜美桃子 2.0": "zh_female_tianmeitaozi_uranus_bigtts",
    "甜美活泼": "ICL_zh_female_tianmei_v1_tob",
    "病娇哥哥": "ICL_zh_male_bingjiaogege_tob",
    "病娇姐姐": "ICL_zh_female_bingjiaojiejie_tob",
    "病娇姐姐 (SC 2.0)": "saturn_zh_female_bingjiaojiejie_tob",
    "病娇姐姐 (Saturn)": "saturn_zh_female_bingjiaojiejie_tob",
    "病娇姐姐 2.0": "saturn_zh_female_bingjiaojiejie_tob",
    "病娇少年": "ICL_zh_male_bingjiaoshaonian_tob",
    "病娇弟弟": "ICL_zh_male_bingjiaodidi_tob",
    "病娇男友": "ICL_zh_male_bingjiaonanyou_tob",
    "病娇白莲": "ICL_zh_male_bingjiaobailian_tob",
    "病娇白莲 (SC 2.0)": "saturn_zh_male_bingjiaobailian_tob",
    "病娇白莲 (Saturn)": "saturn_zh_male_bingjiaobailian_tob",
    "病娇白莲 2.0": "saturn_zh_male_bingjiaobailian_tob",
    "病娇萌妹": "ICL_zh_female_bingjiaomengmei_tob",
    "病弱公子": "ICL_zh_male_bingruogongzi_tob",
    "病弱少女": "ICL_zh_female_bingruoshaonv_tob",
    "病弱少年": "ICL_zh_male_bingruoshaonian_tob",
    "直率英子": "zh_female_naying_mars_bigtts",
    "直率英子 2.0": "zh_female_zhishuaiyingzi_uranus_bigtts",
    "直率青年": "ICL_zh_male_zhishuaiqingnian_tob",
    "知心姐姐": "ICL_zh_female_wenyinvsheng_v1_tob",
    "知性女声": "zh_female_zhixingnvsheng_mars_bigtts",
    "知性女声 2.0": "zh_female_zhixingnv_uranus_bigtts",
    "知性温婉": "ICL_zh_female_zhixingwenwan_tob",
    "知性灿灿": "zh_female_cancan_uranus_bigtts",
    "知性灿灿 (SC 2.0)": "saturn_zh_female_cancan_tob",
    "知性灿灿 (Saturn)": "saturn_zh_female_cancan_tob",
    "知性灿灿 2.0": "zh_female_cancan_uranus_bigtts",
    "知性灿灿 2.0 (Saturn)": "saturn_zh_female_cancan_tob",
    "磁性男嗓": "ICL_zh_male_cixingnansang_tob",
    "磁性男嗓 (SC 2.0)": "saturn_zh_male_cixingnansang_tob",
    "磁性男嗓 (Saturn)": "saturn_zh_male_cixingnansang_tob",
    "磁性男嗓 2.0": "saturn_zh_male_cixingnansang_tob",
    "磁性解说男声": "zh_male_jieshuonansheng_mars_bigtts",
    "磁性解说男声/Morgan": "zh_male_cixingjieshuonan_uranus_bigtts",
    "磁性解说男声/Morgan 2.0": "zh_male_cixingjieshuonan_uranus_bigtts",
    "神秘法师": "ICL_zh_male_shenmifashi_tob",
    "秀丽倩倩": "ICL_zh_female_xiuliqianqian_cs_tob",
    "粘人男友": "ICL_zh_male_naigounanyou_tob",
    "粤语小溏": "zh_female_yueyunv_mars_bigtts",
    "精灵向导": "ICL_zh_female_jinglingxiangdao_1beb294a9e3e_tob",
    "精英青年": "ICL_zh_male_jingyingqingnian_tob",
    "纯澈女生": "ICL_zh_female_feicui_v1_tob",
    "纯真学弟": "ICL_zh_male_chunzhenxuedi_tob",
    "纯真少女": "ICL_zh_female_chunzhenshaonv_e588402fb8ad_tob",
    "绿茶小哥": "ICL_zh_male_lvchaxiaoge_tob",
    "翩翩公子": "ICL_zh_male_pianpiangongzi_tob",
    "胡子叔叔": "ICL_zh_male_huzi_v1_tob",
    "腹黑公子": "ICL_zh_male_fuheigongzi_tob",
    "腹黑公子 (SC 2.0)": "saturn_zh_male_fuheigongzi_tob",
    "腹黑公子 (Saturn)": "saturn_zh_male_fuheigongzi_tob",
    "腹黑公子 2.0": "saturn_zh_male_fuheigongzi_tob",
    "自信青年": "ICL_zh_male_zixinqingnian_tob",
    "自负青年": "ICL_zh_male_zifuqingnian_tob",
    "萌丫头": "zh_female_mengyatou_mars_bigtts",
    "萌丫头/Cutey": "zh_female_mengyatou_uranus_bigtts",
    "萌丫头/Cutey 2.0": "zh_female_mengyatou_uranus_bigtts",
    "蓝银草魂师": "ICL_zh_male_lanyingcaohunshi_v1_tob",
    "解说小明": "zh_male_jieshuoxiaoming_moon_bigtts",
    "解说小明 2.0": "zh_male_jieshuoxiaoming_uranus_bigtts",
    "译制片男": "zh_male_yizhipiannan_uranus_bigtts",
    "译制片男 2.0": "zh_male_yizhipiannan_uranus_bigtts",
    "诡异神秘": "ICL_zh_male_guiyishenmi_tob",
    "调皮公主": "ICL_zh_female_tiaopigongzhu_tob",
    "调皮公主 (SC 2.0)": "saturn_zh_female_tiaopigongzhu_tob",
    "调皮公主 (Saturn)": "saturn_zh_female_tiaopigongzhu_tob",
    "调皮公主 2.0": "saturn_zh_female_tiaopigongzhu_tob",
    "谄媚女声": "zh_female_flattery_mars_bigtts",
    "谄媚女声 2.0": "zh_female_chanmeinv_uranus_bigtts",
    "谄慢女声": "zh_female_flattery_mars_bigtts",
    "豫州子轩": "zh_male_yuzhouzixuan_moon_bigtts",
    "贴心女友": "ICL_zh_female_tiexinnvyou_tob",
    "贴心女友 (SC 2.0)": "saturn_zh_female_tiexinnvyou_tob",
    "贴心女友 (Saturn)": "saturn_zh_female_tiexinnvyou_tob",
    "贴心女友 2.0": "saturn_zh_female_tiexinnvyou_tob",
    "贴心女声": "zh_female_tiexinnvsheng_mars_bigtts",
    "贴心女声/Candy": "zh_female_tiexinnvsheng_uranus_bigtts",
    "贴心女声/Candy 2.0": "zh_female_tiexinnvsheng_uranus_bigtts",
    "贴心妹妹": "ICL_zh_female_yilin_tob",
    "贴心男友": "ICL_zh_male_tiexinnanyou_tob",
    "贴心闺蜜": "ICL_zh_female_xnx_tob",
    "软萌团子": "ICL_zh_female_ruanmengtuanzi_cs_tob",
    "软萌糖糖": "ICL_zh_female_ruanmengtangtang_cs_tob",
    "轻盈朵朵": "ICL_zh_female_qingyingduoduo_cs_tob",
    "轻盈朵朵 (SC 2.0)": "saturn_zh_female_qingyingduoduo_cs_tob",
    "轻盈朵朵 (Saturn)": "saturn_zh_female_qingyingduoduo_cs_tob",
    "轻盈朵朵 2.0": "saturn_zh_female_qingyingduoduo_cs_tob",
    "邪魅女王": "ICL_zh_female_bingjiao3_tob",
    "邪魅御姐": "ICL_zh_female_xiangliangya_v1_tob",
    "邻家女孩": "zh_female_linjianvhai_moon_bigtts",
    "邻家女孩 2.0": "zh_female_linjianvhai_uranus_bigtts",
    "邻家男孩": "zh_male_linjiananhai_moon_bigtts",
    "邻家男孩 2.0": "zh_male_linjiananhai_uranus_bigtts",
    "邻居阿姨": "zh_female_linjuayi_emo_v2_mars_bigtts",
    "邻居阿姨2": "ICL_zh_female_linjuayi_tob",
    "邻居阿姨（多情感）": "zh_female_linjuayi_emo_v2_mars_bigtts",
    "醇厚低音": "ICL_zh_male_buyan_v1_tob",
    "醋精男友": "ICL_zh_male_cujingnanyou_tob",
    "醋精男友 (SC 2.0)": "saturn_zh_male_cujingnanyou_tob",
    "醋精男友 (Saturn)": "saturn_zh_male_cujingnanyou_tob",
    "醋精男友 2.0": "saturn_zh_male_cujingnanyou_tob",
    "醋精男生": "ICL_zh_male_cujingnansheng_tob",
    "闷油瓶小哥": "ICL_zh_male_menyoupingxiaoge_ffed9fc2fee7_tob",
    "阳光洋洋": "ICL_zh_male_yangguangyangyang_cs_tob",
    "阳光阿辰": "zh_male_qingyiyuxuan_mars_bigtts",
    "阳光青年": "zh_male_yangguangqingnian_emo_v2_mars_bigtts",
    "阳光青年 2.0": "zh_male_yangguangqingnian_uranus_bigtts",
    "阳光青年（多情感）": "zh_male_yangguangqingnian_emo_v2_mars_bigtts",
    "霸气青叔 2.0": "zh_male_baqiqingshu_uranus_bigtts",
    "霸道少爷": "ICL_zh_male_badaoshaoye_tob",
    "霸道少爷 (SC 2.0)": "saturn_zh_male_badaoshaoye_tob",
    "霸道少爷 (Saturn)": "saturn_zh_male_badaoshaoye_tob",
    "霸道少爷 2.0": "saturn_zh_male_badaoshaoye_tob",
    "霸道总裁": "ICL_zh_male_badaozongcai_v1_tob",
    "青涩小生": "ICL_zh_male_qingsenaigou_tob",
    "青涩青年": "ICL_zh_male_qingseqingnian_tob",
    "顾姐": "zh_female_gujie_mars_bigtts",
    "顾姐 2.0": "zh_female_gujie_uranus_bigtts",
    "风发少年": "ICL_zh_male_fengfashaonian_tob",
    "风发少年 (SC 2.0)": "saturn_zh_male_fengfashaonian_tob",
    "风发少年 (Saturn)": "saturn_zh_male_fengfashaonian_tob",
    "风发少年 2.0": "saturn_zh_male_fengfashaonian_tob",
    "高冷御姐": "zh_female_gaolengyujie_emo_v2_mars_bigtts",
    "高冷御姐 2.0": "zh_female_gaolengyujie_uranus_bigtts",
    "高冷御姐2": "zh_female_gaolengyujie_moon_bigtts",
    "高冷御姐（多情感）": "zh_female_gaolengyujie_emo_v2_mars_bigtts",
    "高冷总裁": "ICL_zh_male_gaolengzongcai_tob",
    "高冷沉稳": "zh_male_bv139_audiobook_ummv3_bigtts",
    "高冷沉稳 2.0": "zh_male_gaolengchenwen_uranus_bigtts",
    "魅力女友": "zh_female_meilinvyou_emo_v2_mars_bigtts",
    "魅力女友 2.0": "zh_female_meilinvyou_uranus_bigtts",
    "魅力女友2": "zh_female_meilinvyou_moon_bigtts",
    "魅力女友（多情感）": "zh_female_meilinvyou_emo_v2_mars_bigtts",
    "魅力苏菲": "zh_female_sophie_conversation_wvae_bigtts",
    "魅力苏菲 2.0": "zh_female_sophie_uranus_bigtts",
    "鲁班七号": "zh_male_lubanqihao_mars_bigtts",
    "鲁班七号 2.0": "zh_male_lubanqihao_uranus_bigtts",
    "鸡汤女": "zh_female_jitangnv_uranus_bigtts",
    "鸡汤女 2.0": "zh_female_jitangnv_uranus_bigtts",
    "鸡汤妹妹": "zh_female_jitangmeimei_mars_bigtts",
    "鸡汤妹妹/Hope": "zh_female_jitangmei_uranus_bigtts",
    "鸡汤妹妹/Hope 2.0": "zh_female_jitangmei_uranus_bigtts",
    "黑猫侦探社咪仔": "zh_female_mizai_uranus_bigtts",
    "黑猫侦探社咪仔 2.0": "zh_female_mizai_uranus_bigtts",
    "黯刃秦主": "ICL_zh_male_anrenqinzhu_cd62e63dcdab_tob",
}

voice_options_small = {
    "亲切女声": "BV007_streaming",
    "亲切男声": "BV008_streaming",
    "促销女声": "BV402_streaming",
    "促销男声": "BV401_streaming",
    "儒雅青年": "BV102_streaming",
    "动漫小新": "BV050_streaming",
    "动漫海星": "BV417_streaming",
    "动漫海绵": "BV063_streaming",
    "反卷青年": "BV120_streaming",
    "古风少御": "BV115_streaming",
    "天才少女": "BV421_streaming",
    "天才童声": "BV061_streaming",
    "奶气萌娃": "BV051_streaming",
    "小萝莉": "BV064_streaming",
    "开朗青年": "BV004_streaming",
    "影视解说小帅": "BV411_streaming",
    "影视解说小美": "BV412_streaming",
    "慈爱姥姥": "BV157_streaming",
    "懒小羊": "BV426_streaming",
    "擎苍": "BV701_streaming",
    "擎苍 2.0": "BV701_V2_streaming",
    "新闻女声": "BV011_streaming",
    "新闻男声": "BV012_streaming",
    "智慧老者": "BV158_streaming",
    "沉稳解说男": "BV142_streaming",
    "活力解说男": "BV410_streaming",
    "活泼女声": "BV005_streaming",
    "清新文艺女声": "BV428_streaming",
    "温柔小哥": "BV033_streaming",
    "温柔淑女": "BV104_streaming",
    "潇洒青年": "BV143_streaming",
    "灿灿": "BV700_streaming",
    "灿灿 2.0": "BV700_V2_streaming",
    "炀炀": "BV705_streaming",
    "甜宠少御": "BV113_streaming",
    "甜美小源": "BV405_streaming",
    "直播一姐": "BV418_streaming",
    "知性女声": "BV009_streaming",
    "知性姐姐-双语": "BV034_streaming",
    "磁性男声": "BV006_streaming",
    "童童": "BV415_streaming",
    "纨绔青年": "BV159_streaming",
    "解说小帅-多情感": "BV437_streaming",
    "译制片男声": "BV408_streaming",
    "诚诚": "BV419_streaming",
    "说唱小哥": "BR001_streaming",
    "质朴青年": "BV100_streaming",
    "超自然音色-梓梓": "BV406_streaming",
    "超自然音色-梓梓2.0": "BV406_V2_streaming",
    "超自然音色-燃燃": "BV407_streaming",
    "超自然音色-燃燃2.0": "BV407_V2_streaming",
    "通用女声": "BV001_streaming",
    "通用女声 2.0": "BV001_V2_streaming",
    "通用男声": "BV002_streaming",
    "通用赘婿": "BV119_streaming",
    "阳光男声": "BV056_streaming",
    "阳光青年": "BV123_streaming",
    "霸气青叔": "BV107_streaming",
    "鸡汤女声": "BV403_streaming",
}

voice_options = {
    "big": voice_options_big,
    "small": voice_options_small,
}

volcano_voice_options = voice_options

character_options = {**voice_options_big, **voice_options_small}

voice_model_type_options = ("big", "small")


def get_volcano_voice_type(voice_character: str) -> Literal["big", "small"]:
    if voice_character in voice_options_small:
        return "small"
    if voice_character in voice_options_big:
        return "big"
    raise KeyError(f"Unknown volcovoice character: {voice_character}")


def get_voice_options(model_type: str = "all") -> dict[str, str]:
    normalized = (model_type or "all").lower()
    if normalized == "all":
        return character_options
    if normalized == "big":
        return voice_options_big
    if normalized == "small":
        return voice_options_small
    raise ValueError("model_type must be one of: all, big, small")

def get_v2_voices(support_instruct_only: bool = False) -> list[str]:
    """
    Returns a list of voice characters that belong to the V2 family (Uranus 2.0 / Saturn 2.0 / Jupiter).
    If support_instruct_only is True, filters to Saturn and Uranus voices which support expressive instructions.
    """
    v2_voices = []
    for char, code in character_options.items():
        code_lower = code.lower()
        if "uranus" in code_lower or "saturn" in code_lower or "jupiter" in code_lower:
            if support_instruct_only:
                if "saturn" in code_lower or "uranus" in code_lower:
                    v2_voices.append(char)
            else:
                v2_voices.append(char)
    return v2_voices


__all__ = [
    'voice_options_big',
    'voice_options_small',
    'voice_options',
    'volcano_voice_options',
    'character_options',
    'voice_model_type_options',
    'get_volcano_voice_type',
    'get_voice_options',
    'get_v2_voices',
    'voice_enums_meta',
]

from models.volcano_online_voice_enums_meta import voice_enums_meta
